import type { TimelinePhase } from "./types";

export const commerceTimelineData: TimelinePhase[] = [
  {
    id: "pre-commerce",
    title: "PRE COMMERCE",
    description: "The advent of GSM technology and mobile internet.",
    startYear: 2000,
    endYear: 2007,
    theme: "orange",
    events: [
      {
        id: "event-1",
        year: 2000,
        yearLabel: "Early 90s/2000s",
        title: "Kenya",
        description: [
          "The telecom industry was liberalised in",
          "the 2000, creating a demand for fixed",
          "line connections",
        ],
        vector: "vector-a",
        contentPosition: "top-left",
      },
      {
        id: "event-2",
        year: 2002,
        yearLabel: "2002",
        title: "South Africa",
        description: [
          "TThe Global System for Mobile, the global",
          "standard for mobile communication",
          "was implemented in 1993.",
        ],
        vector: "vector-b",
        contentPosition: "top-left",
      },
      {
        id: "event-3",
        year: 2006,
        yearLabel: "2006",
        title: "Nigeria",
        description: [
          "TThe Global System for Mobile, the global",
          "standard for mobile communication",
          "was implemented in 1993.",
        ],
        vector: "vector-b",
        contentPosition: "top-left",
      },
      {
        id: "event-66",
        year: 2007,
        yearLabel: "2007",
        title: "Nigeria",
        description: [
          "TThe Global System for Mobile, the global",
          "standard for mobile communication",
          "was implemented in 1993.",
        ],
        vector: "vector-c",
        contentPosition: "top-left",
      },
    ],
  },
  {
    id: "explosion",
    title: "EXPLOSION",
    description: "Jumia and Konga Launch",
    startYear: 2009,
    endYear: 2016,
    theme: "red",
    events: [
      {
        id: "event-4",
        year: 2009,
        yearLabel: "2009",
        title: "Jumia",
        description: [
          "Founded by Rocket Internet, Africa Internet",
          "Group (AIG) launched Jumia in Nigeria in 2012",
          "and soon expands to Morocco, South Africa,",
          "and Egypt",
        ],
        vector: "vector-a",
        contentPosition: "top-left",
      },
      {
        id: "event-5",
        year: 2010,
        yearLabel: "2010",
        title: "Konga",
        description: [
          "Launched in Nigeria in July 2012 by Havard",
          "MBA grad and serial entrepreneur, Sim Shagaya",
          "as an online platform that specialised",
          "in baby and personal care products",
        ],
        vector: "vector-b",
        contentPosition: "top-left",
      },
      {
        id: "event-6",
        year: 2011,
        yearLabel: "2012",
        title: "Kalahari",
        description: [
          "Naspers-owned Kalahari a South Africa based ",
          "online platform merges with its toughest competitor",
          "Takealot. Kalahari was nixed in 2016 and",
          "in 2018 Naspers acquired a 96% stake in Takealot",
        ],
        vector: "vector-b",
        contentPosition: "top-left",
      },
      {
        id: "event-33",
        year: 2012,
        yearLabel: "2012",
        title: "Kalahari",
        description: [
          "Naspers-owned Kalahari a South Africa based ",
          "online platform merges with its toughest competitor",
          "Takealot. Kalahari was nixed in 2016 and",
          "in 2018 Naspers acquired a 96% stake in Takealot",
        ],
        vector: "vector-b",
        contentPosition: "top-left",
      },
      {
        id: "event-44",
        year: 2013,
        yearLabel: "2012",
        title: "Kalahari",
        description: [
          "Naspers-owned Kalahari a South Africa based ",
          "online platform merges with its toughest competitor",
          "Takealot. Kalahari was nixed in 2016 and",
          "in 2018 Naspers acquired a 96% stake in Takealot",
        ],
        vector: "vector-b",
        contentPosition: "top-left",
      },
      {
        id: "event-00",
        year: 2014,
        yearLabel: "2012",
        title: "Kalahari",
        description: [
          "Naspers-owned Kalahari a South Africa based ",
          "online platform merges with its toughest competitor",
          "Takealot. Kalahari was nixed in 2016 and",
          "in 2018 Naspers acquired a 96% stake in Takealot",
        ],
        vector: "vector-b",
        contentPosition: "top-left",
      },
      {
        id: "event-99",
        year: 2016,
        yearLabel: "2012",
        title: "Kalahari",
        description: [
          "Naspers-owned Kalahari a South Africa based ",
          "online platform merges with its toughest competitor",
          "Takealot. Kalahari was nixed in 2016 and",
          "in 2018 Naspers acquired a 96% stake in Takealot",
        ],
        vector: "vector-b",
        contentPosition: "top-left",
      },
    ],
  },
  {
    id: "growth",
    title: "GROWTH PHASE",
    description: "Safaricom launches eCommerce store",
    startYear: 2017,
    endYear: 2020,
    theme: "red",
    events: [
      {
        id: "event-10",
        year: 2017,
        yearLabel: "2017",
        title: "Safaricom",
        description: [
          "Founded by Rocket Internet, Africa Internet",
          "Group (AIG) launched Jumia in Nigeria in 2012",
          "and soon expands to Morocco, South Africa,",
          "and Egypt",
        ],
        vector: "vector-a",
        contentPosition: "top-left",
      },
      {
        id: "event-15",
        year: 2018,
        yearLabel: "2018",
        title: "DHL & Mall for Africa",
        description: [
          "DHL partners with MallforAfrica to launch",
          "a new online shopping app, AfricaeShop, and",
          "expands to 34 African countries.",
        ],
        vector: "vector-b",
        contentPosition: "top",
      },
      {
        id: "event-16",
        year: 2019,
        yearLabel: "2019",
        title: "Kalahari",
        description: [
          "Naspers-owned Kalahari a South Africa based ",
          "online platform merges with its toughest competitor",
          "Takealot. Kalahari was nixed in 2016 and",
          "in 2018 Naspers acquired a 96% stake in Takealot",
        ],
        vector: "vector-c",
        contentPosition: "center-left",
      },
      {
        id: "event-17",
        year: 2019,
        yearLabel: "2019",
        title: "Kalahari",
        description: [
          "Touted as Africa's first unicorn and active",
          "in 14 countries, Jumia becomes the first African",
          "startup to be listed on the New York",
          "Stock Exchange",
        ],
        vector: "vector-e",
        contentPosition: "top-left",
      },
    ],
  },
];
